run-name: CI/CD to AWS by @${{ github.actor }}
name: CD to lightsail

on:
  workflow_dispatch:
    permissions:
      users:
        - saJaeHyukc
        - Zamoca42

jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests with Coverage
        run: npm run test:cov

      - name: Run Lint
        run: npm run lint

  deploy:
    runs-on: ubuntu-latest
    needs: test-lint
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          key: ${{ secrets.LIGHTSAIL_KEY }}
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: ${{ secrets.LIGHTSAIL_NAME }}
          port: ${{ secrets.LIGHTSAIL_PORT }}
          script: |
            cd ${{ secrets.LIGHTSAIL_PATH }} 
            
            if [ -f pid.txt ]; then

              pid=$(cat pid.txt)

              kill $pid
              echo "Stopped the previous process with PID $pid"
            fi

            git pull origin main
            npm install
            npm run build
            nohup npm run start:prod > output.log 2>&1 &
            echo $! > pid.txt
