run-name: CI/CD to AWS by @${{ github.actor }}

on:
  workflow_dispatch:
    permissions:
      users:
        - saJaeHyukc
        - Zamoca42

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Run Tests with Coverage
        run: npm run test:cov

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Run Lint
        run: npm run lint

  deploy:
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          key: ${{ secrets.LIGHTSAIL_KEY }}
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: ${{ secrets.LIGHTSAIL_NAME }}
          port: ${{ secrets.LIGHTSAIL_PORT }}
          # LIGHTSAIL_PATH -> /home/backend
          script: |
            cd ${{ secrets.LIGHTSAIL_PATH }} 
            git pull origin main
            rm -rf dist
            npm install
            npm run build
            npm run start:prod
