run-name: CI/CD to AWS by @${{ github.actor }}
name: CD to EC2

on:
  workflow_dispatch:
    permissions:
      users:
        - saJaeHyukc
        - Zamoca42

jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: npm install, test and lint
        run: |
          npm ci
          npm run test:cov
          npm run lint

  deploy:
    runs-on: ubuntu-latest
    needs: test-lint
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.AWS_SECRET_KEY }}
          host: ${{ secrets.AWS_INSTANCE_IP }}
          username: ${{ secrets.LIGHTSAIL_NAME }}
          port: ${{ secrets.AWS_INSTANCE_PORT }}
          script: |
            cd ${{ secrets.AWS_INSTANCE_PATH }} 

            if [ -f pid.txt ]; then

              pid=$(cat pid.txt)

              kill $pid
              echo "Stopped the previous process with PID $pid"
            fi

            git pull origin main
            npm install
            npm run build
            nohup npm run start:prod > output.log 2>&1 &
            echo $! > pid.txt