name: CI

on:
  push:
    branches: [feature/*]

jobs:
  setup-node:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        run: npm ci

  test:
    runs-on: ubuntu-latest
    needs: setup-node
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Tests with Coverage
        run: npm run test:cov

  lint:
    runs-on: ubuntu-latest
    needs: setup-node
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Lint
        run: npm run lint
